### ISSUE TITLE
Conflict with dependency

### ISSUE THREAD

**Issue by SimonHaenle2** [dpreussler/Diacetyl#3]
Hey Danny, 
saw you at droidcon and wanted to use diacetyl.
Unfortunately when i try to add the dependency, this gradle error occurs:

Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
Warning:Conflict with dependency 'com.android.support:recyclerview-v7'. Resolved versions for app (23.1.1) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

Any Idea how to fix it?
Best regards,
Simon

**Comment by dpreussler** [comment]
import the following way:

```
testCompile ('de.jodamob.android:diacetyl:0.5.1') {
        exclude group:"com.android.support"
}
```

**Comment by SimonHaenle2** [comment]
Thanks man, you're the best.
